#!/usr/bin/env python3
import hashlib
import json
import os
import re
import unicodedata
from datetime import datetime, timezone
from pathlib import Path

from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload


REPO_ROOT = Path(__file__).resolve().parent.parent
PHOTOS_DIR = REPO_ROOT / "public" / "photos"
CONTENT_DIR = REPO_ROOT / "src" / "content" / "photos"
MANIFEST_PATH = CONTENT_DIR / ".drive-sync-manifest.json"


def slugify(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", normalized.lower()).strip("-")
    return slug or "photo"


def title_from_stem(stem: str) -> str:
    clean = re.sub(r"[_\-]+", " ", stem).strip()
    return clean.title() or "Photo"


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def ensure_dirs() -> None:
    PHOTOS_DIR.mkdir(parents=True, exist_ok=True)
    CONTENT_DIR.mkdir(parents=True, exist_ok=True)


def load_manifest() -> dict:
    if not MANIFEST_PATH.exists():
        return {"files": {}}
    try:
        return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {"files": {}}


def save_manifest(manifest: dict) -> None:
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def build_drive_client():
    raw_json = os.getenv("GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON")
    if not raw_json:
        raise RuntimeError("GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON is required.")
    service_account_info = json.loads(raw_json)
    creds = service_account.Credentials.from_service_account_info(
        service_account_info,
        scopes=["https://www.googleapis.com/auth/drive.readonly"],
    )
    return build("drive", "v3", credentials=creds, cache_discovery=False)


def list_image_files(drive_client, folder_id: str):
    query = f"'{folder_id}' in parents and trashed = false and mimeType contains 'image/'"
    page_token = None
    files = []
    while True:
        response = (
            drive_client.files()
            .list(
                q=query,
                fields="nextPageToken, files(id, name, mimeType, md5Checksum, modifiedTime)",
                orderBy="modifiedTime desc",
                pageSize=1000,
                pageToken=page_token,
                supportsAllDrives=True,
                includeItemsFromAllDrives=True,
            )
            .execute()
        )
        files.extend(response.get("files", []))
        page_token = response.get("nextPageToken")
        if not page_token:
            break
    return files


def unique_slug(base_slug: str, used_slugs: set[str], file_id: str) -> str:
    if base_slug not in used_slugs:
        used_slugs.add(base_slug)
        return base_slug
    candidate = f"{base_slug}-{file_id[:8]}"
    used_slugs.add(candidate)
    return candidate


def build_frontmatter(title: str, date_value: str, cover_path: str, category: str) -> str:
    return (
        "---\n"
        f'title: "{title}"\n'
        'description: "Imported from Google Drive."\n'
        f"date: {date_value}\n"
        f'cover: "{cover_path}"\n'
        f'category: "{category}"\n'
        "draft: false\n"
        "---\n\n"
        "Auto-generated by Google Drive sync. Edit this entry to add custom description or story.\n"
    )


def download_file(drive_client, file_id: str, target_path: Path) -> None:
    request = drive_client.files().get_media(fileId=file_id, supportsAllDrives=True)
    with target_path.open("wb") as out:
        downloader = MediaIoBaseDownload(out, request)
        done = False
        while not done:
            _, done = downloader.next_chunk()


def main() -> int:
    folder_id = os.getenv("GOOGLE_DRIVE_FOLDER_ID")
    if not folder_id:
        raise RuntimeError("GOOGLE_DRIVE_FOLDER_ID is required.")
    category = os.getenv("PHOTO_DEFAULT_CATEGORY", "General")

    ensure_dirs()
    drive = build_drive_client()
    manifest = load_manifest()
    manifest_files = manifest.setdefault("files", {})
    used_slugs = {entry.get("slug") for entry in manifest_files.values() if entry.get("slug")}
    used_slugs.discard(None)

    files = list_image_files(drive, folder_id)
    seen_ids = set()
    downloaded_count = 0
    created_md_count = 0

    for remote_file in files:
        file_id = remote_file["id"]
        name = remote_file["name"]
        modified_time = remote_file.get("modifiedTime", "")
        checksum = remote_file.get("md5Checksum")
        seen_ids.add(file_id)

        existing = manifest_files.get(file_id, {})
        slug = existing.get("slug")
        if not slug:
            slug = unique_slug(slugify(Path(name).stem), used_slugs, file_id)

        target_photo = PHOTOS_DIR / name
        should_download = True
        if target_photo.exists() and checksum and existing.get("md5Checksum") == checksum:
            should_download = False
        if target_photo.exists() and not checksum:
            should_download = False

        if should_download:
            download_file(drive, file_id, target_photo)
            downloaded_count += 1

        md_path = CONTENT_DIR / f"{slug}.md"
        if not md_path.exists():
            date_value = datetime.now(timezone.utc).date().isoformat()
            if modified_time:
                try:
                    parsed = datetime.fromisoformat(modified_time.replace("Z", "+00:00"))
                    date_value = parsed.date().isoformat()
                except ValueError:
                    pass
            title = title_from_stem(Path(name).stem)
            cover_path = f"/photos/{name}"
            md_path.write_text(
                build_frontmatter(title=title, date_value=date_value, cover_path=cover_path, category=category),
                encoding="utf-8",
            )
            created_md_count += 1

        manifest_files[file_id] = {
            "name": name,
            "slug": slug,
            "md5Checksum": checksum,
            "lastSyncedAt": datetime.now(timezone.utc).isoformat(),
        }

    removed = [fid for fid in list(manifest_files.keys()) if fid not in seen_ids]
    for fid in removed:
        manifest_files.pop(fid, None)

    save_manifest(manifest)
    print(f"Synced {len(files)} files, downloaded {downloaded_count}, created {created_md_count} markdown entries.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
